language: php
# Tests will be for each version in `php` combined with each node version in `env`
php:
#  - 5.5
#  - 5.6
#  - 7.0
  - 7.1
env:
#  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="8"
before_install:
  - composer self-update
  - composer clear-cache
#  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - . $HOME/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - npm install npm@latest -g
install:
  - npm install
  - npm run setup
before_script:
  - php --version
  - node --version
  - npm --version
script: 'npm run compile && npm test'
notifications:
  email:
    on_success: never
    on_failure: always
  flowdock:
    secure: RBLFcGBNV8iBA3pBGqGzq5o2Kt+X0IESDtuWnamGurhXItdd0Qh8LZwGmbcZdBuncJQ/WvC5/umCZykf0BeMOiu5TnhJKH3ett0qQT8dxJI9aykwbk/+xyCX09tQJ6jejhcDmu394SUlXYb8DBPnlmE345EVbtjFt9Wxo+ZskCo=
