# To override values here make a file named 'Gruntconfig--custom.yml' - it will be git ignored

plDir: pattern-lab/
jsDir: js/
scssDir: scss/
scssDest: css/style.css
scssConfigRoot: ./
buildModernizrAtStart: true
regressionTestRoot: pattern-lab/source/_patterns/
features:
  scss: true
  patternLab: true
  icons: true
  browserSync: true
browserSync:
  port: 3050
  watchFiles:
    - css/style.css
    - js/*.js
#  domain: mysite.dev # enable when full CMS is set up
  serverDir: ./
  serverPath: pattern-lab/public/
  openBrowserAtStart: false
  # requires above to be true; allows non-default browser to open
  #browser: Google Chrome
