v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
cleanPublic: 'true'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: ../../dist/public/
sourceDir: ../../source/
defaultPattern: all
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
lineageMatch: >-
  {%([ ]+)?include(
  |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  faker:
    enabled: true
    locale: en_US
  twigNamespaces:
    enabled: true
    namespaces:
      base:
        paths:
          - ../../source/_patterns/00-base
          - ../../source/_patterns/00-base/05-colors
          - ../../source/_patterns/00-base/10-spacing
          - ../../source/_patterns/00-base/15-typography/fonts
          - ../../source/_patterns/00-base/15-typography/headings
          - ../../source/_patterns/00-base/15-typography/lists
          - ../../source/_patterns/00-base/15-typography/text
          - ../../source/_patterns/00-base/breakpoints
          - ../../source/_patterns/00-base/grids
          - ../../source/_patterns/00-base/utilities/borders
      atoms:
        paths:
          - ../../source/_patterns/01-atoms
          - ../../source/_patterns/01-atoms/buttons
          - ../../source/_patterns/01-atoms/images
      molecules:
        paths:
          - ../../source/_patterns/02-molecules
          - ../../source/_patterns/02-molecules/card
          - ../../source/_patterns/02-molecules/test
      organisms:
        paths:
          - ../../source/_patterns/03-organisms
      templates:
        paths:
          - ../../source/_patterns/04-templates
      pages:
        paths:
          - ../../source/_patterns/05-pages
