v: 2.6.0
overrideConfig: false
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
  - fonts
  - icons
cleanPublic: 'true'
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: ../../dist/public/
sourceDir: ../../source/
defaultPattern: all
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
lineageMatch: >-
  {%([ ]+)?include(
  |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
plugins:
  faker:
    enabled: true
    locale: en_US
  twigNamespaces:
    enabled: true
    namespaces:
      base:
        paths:
          - ../../source/_patterns/00-base
      atoms:
        paths:
          - ../../source/_patterns/01-atoms
          - ../../source/_patterns/01-atoms/images
          - ../../source/_patterns/01-atoms/buttons
      molecules:
        paths:
          - ../../source/_patterns/02-molecules
          - ../../source/_patterns/02-molecules/card
      organisms:
        paths:
          - ../../source/_patterns/03-organisms
      templates:
        paths:
          - ../../source/_patterns/04-templates
      pages:
        paths:
          - ../../source/_patterns/05-pages
